baseURL = "https://vorblog.azurewebsites.net/"
languageCode = "en-us"
title = "Voice of Repentance"

[markup]
  # To be able to use all Prism plugins, the theme enables unsafe rendering by default
  [markup.goldmark.renderer]
    unsafe = true

[build]
  # Merge build config of the theme
  _merge = "deep"

# Module configuration for the Gruvbox theme
[module]
  [[module.imports]]
    path = "github.com/schnerring/hugo-theme-gruvbox"
  [[module.imports]]
    path = "github.com/schnerring/hugo-mod-json-resume"
    [[module.imports.mounts]]
      source = "data"
      target = "data"
    [[module.imports.mounts]]
      source = "layouts"
      target = "layouts"
    [[module.imports.mounts]]
      source = "assets/css/json-resume.css"
      target = "assets/css/critical/44-json-resume.css"
  [[module.mounts]]
    # required by hugo-mod-json-resume
    source = "node_modules/simple-icons/icons"
    target = "assets/simple-icons"
  [[module.mounts]]
    source = "assets"
    target = "assets"
  [[module.mounts]]
    source = "layouts"
    target = "layouts"
  [[module.mounts]]
    source = "static"
    target = "static"
  [[module.mounts]]
    source = "node_modules/prismjs"
    target = "assets/prismjs"
  [[module.mounts]]
    source = "node_modules/prism-themes/themes"
    target = "assets/prism-themes"
  [[module.mounts]]
    source = "node_modules/typeface-fira-code/files"
    target = "static/fonts"
  [[module.mounts]]
    source = "node_modules/typeface-roboto-slab/files"
    target = "static/fonts"
  [[module.mounts]]
    source = "node_modules/@tabler/icons/icons"
    target = "assets/tabler-icons"
  [[module.mounts]]
    # Add hugo_stats.json to Hugo's server watcher
    source = "hugo_stats.json"
    target = "assets/watching/hugo_stats.json"

# Site parameters
[params]
  description = "A blog test dedicated to sharing insights, reflections, and teachings that inspire spiritual growth and transformation."
  author = "Voice of Repentance"
  
  # Logo settings
  [params.Logo]
    Text = "Voice of Repentance"
  
  # Theme settings
  # gray red green yellow blue purple aqua orange, defaults to blue
  themeColor = "yellow"
  # soft medium hard, defaults to medium
  themeContrast = "medium"
  
  # Tag cloud configuration
  [params.tagCloud]
    enable = true
    minFontSizeRem = 0.8
    maxFontSizeRem = 2.0
  
  # Prism syntax highlighting configuration
  [params.prism]
    languages = [
      "markup",
      "css",
      "clike",
      "javascript",
      "bash",
      "python",
      "yaml",
      "markdown"
    ]
    plugins = [
      # Core plugins (already configured)
      "normalize-whitespace",
      "toolbar",
      "copy-to-clipboard",
      "line-numbers",
      
      # Additional recommended plugins for ministry content
      "line-highlight",     # Highlight specific verses or passages
      "show-language",     # Clearly indicate different languages (Hebrew, Greek, etc.)
      "autolinker",        # Automatically link to biblical references
      "match-braces",      # Helpful for showing structure in complex theological concepts
      "highlight-keywords" # Emphasize important theological terms
    ]

# Navigation menu
[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    identifier = "posts"
    name = "Posts"
    url = "/posts/"
    weight = 2
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 3
